from time import time


domains_1 = [
    'buyessayfriend.com',
    'payforessay.net',
    'buyessayclub.com',
    'essayshark.com',
    'www.wiseessays.com',
    'justbuyessay.com',
    'academized.com',
    'www.customwritings.com',
    'buyessay.net',
    'buyessayonline.org',
    'buyessay.org',
    'ibuyessay.com',
    'papernow.org',
    'buyessay.co.uk',
    'ukwritings.com',
    'www.masterpapers.com',
    'grademiners.com',
    'edubirdie.com',
    'australianhelp.com',
    'www.ultius.com',
    'samedayessay.com',
    'ukessay.com',
    'bestessay4u.com',
    'essays24.org',
    'waywrite.com',
    'essayyoda.com',
    'royalessays.co.uk',
    'writersperhour.com',
    'writemyessay.services',
    'www.affordable-papers.net',
    'www.npr.org',
    'papercheap.co.uk',
    'www.privatewriting.com',
    'www.ukessays.com',
    'customessayhero.org',
    'buyessayonline.com',
    'pay-for-essay.co.uk',
    'www.essay-company.com',
    'www.buyessaytoday.com',
    'papersowl.com',
    'bid4papers.com',
    'essayclick.net',
    'cheapwritingservice.com',
    'ibuyessayonline.com',
    'buyessays.onl',
    'myassignmenthelp.com',
    'domywriting.com',
    'www.ozessay.com.au',
    'www.evoessay.com',
    'www.bestessays.com.au',
    'essayontime.com.au',
    'www.essaymasters.co.uk',
    'thevarsity.ca',
    'www.bestcustomwriting.com',
    'essayltd.com',
    'essayroo.com',
    'coolessay.net',
    'mycustomessay.com',
    'www.buyessayscheap.com',
    'www.trustpilot.com',
    'paperell.com',
    'www.essaysdeluxe.com',
    'primewritings.com',
    'www.essayempire.co.uk',
    'www.turnitin.com',
    'www.huffingtonpost.co.uk',
    'twitter.com',
    'darwinessay.net',
    'perfectessaysonline.com',
    'www.usessay.com',
    'buyessaysafe.com',
    'essaypro.com',
    'customwritingsservices.com',
    'gpalabs.com',
    'cheap-essays-online.com',
    'www.affordablepapers.com',
    'samedayessay.org',
    'snowdropfoundation.org',
    'expert-writers.net',
    'www.freshessays.com',
    'buyessay4me.com',
    'smartwritingservice.com',
    'cheapessaywritings24.com',
    'www.6dollaressay.com',
    'chicessays.com',
    'www.essaytigers.com',
    'www.buyanessay.com',
    'www.bidforessay.com',
    'essay-online.com',
    'cheapwritinghelp.com',
    'aussieessaywriter.com.au',
    'eduaidguru.com',
    'ozzz.org',
    'www.kingessay.co.uk',
    'essaywritingstore.com',
    'www.nationalautismcenter.org',
    'www.buy-cheapessay.com',
    'buyessays.us'
]


domains_2 = [
    'buyessayfriend.com',
    'payforessay.net',
    'buyessayonline.org',
    'buyessayclub.com',
    'academized.com',
    'www.wiseessays.com',
    'essayshark.com',
    'justbuyessay.com',
    'edubirdie.com',
    'www.customwritings.com',
    'buyessayonline.com',
    'ukwritings.com',
    'papernow.org',
    'ibuyessay.com',
    'grademiners.com',
    'www.masterpapers.com',
    'ukessay.com',
    'buyessay.co.uk',
    'australianhelp.com',
    'essays24.org',
    'papercheap.co.uk',
    'writersperhour.com',
    'buyessay.net',
    'www.ultius.com',
    'paperell.com',
    'essayyoda.com',
    'www.npr.org',
    'essayroo.com',
    'www.buyessaytoday.com',
    'ibuyessayonline.com',
    'essayontime.com.au',
    'bid4papers.com',
    'royalessays.co.uk',
    'www.ozessay.com.au',
    'essayclick.net',
    'papersowl.com',
    'order-essay-online.net',
    'waywrite.com',
    'smartwritingservice.com',
    'senperfect.com',
    'samedayessay.com',
    'bestessay4u.com',
    'edusson.com',
    'cheapessaywritings24.com',
    'essay-online.com',
    'weeklyessay.com',
    'edubirdies.org',
    'kingessays.com',
    'www.essaymasters.co.uk',
    'www.the-essays.com',
    'edujungles.com',
    'speedypaper.com',
    'www.essaysdeluxe.com',
    'customessayhero.org',
    'buyessay.org',
    'www.6dollaressay.com',
    'www.essayempire.co.uk',
    'pay-for-essay.co.uk',
    'www.buyonlineessay.co.uk',
    'studybay.com',
    'cheap-essays-online.com',
    'domywriting.com',
    'essayassignmenthelp.com.au',
    'eliteessaywriters.com',
    'www.essaydone.co.uk',
    'writemyessaysclub.com',
    'www.essay-company.com',
    'essayltd.com',
    'coolessay.net',
    'writemytermpapers.com',
    'www.bestcustomwriting.com',
    'www.collegepaperworld.com',
    'www.affordable-papers.net',
    'paperslounge.com',
    'writemypaperhub.com',
    'www.essaywritinglab.co.uk',
    'www.buyessayscheap.com',
    'www.essaymill.com',
    'www.theguardian.com',
    'www.essaypanda.org',
    'buyessaysafe.com',
    'chicessays.com',
    'www.buyessaysonline.org',
    'order.studentshare.org',
    'studicus.com',
    'ewritingservice.com',
    'studyjumper.com',
    'buyessay4me.com',
    'www.freelancehouse.co.uk',
    'eduaidguru.com',
    'scoobydomyessay.com',
    'darwinessay.net',
    'www.quora.com',
    'expert-writers.net',
    'www.4students.us',
    'bestessayservice.org',
    'www.onlinecollegeessay.com',
    'oxessays.com',
    'www.radiumcrm.com'
]

t1 = time()


domains_1 = set(domains_1)
domains_2 = set(domains_2)

result = domains_1 - domains_2

print(result)


# # Good code!
# big_list = domains_1 + domains_2
# uniq_domins = set(big_list)
# uniq_domins_list = list(uniq_domins)


# # Bad code!
# uniq_domins_list = []
# for dom in big_list:
#     if dom not in uniq_domins_list:
#         uniq_domins_list.append(dom)
# uniq_domins_list.sort()
#
#
# t2 = time()
#
# print(f'domains_1: {len(domains_1)} items')
# print(f'domains_2: {len(domains_2)} items')
# print(f'big_list: {len(big_list)} items')
# print(f'uniq_domins_list: {len(uniq_domins_list)} items')
#
# print('Working time is: ', t2 - t1)
